// generated by KidsBlock
#include <Arduino.h>

const int servopin = 4;
int set_angle(int angle)
{
  int servo_angle = map(angle, 0, 180, 25, 128);
  return servo_angle;
}

long distance = 0;

long a1 = 0;

long a2 = 0;

float checkdistance() {
  digitalWrite(18, LOW);
  delayMicroseconds(2);
  digitalWrite(18, HIGH);
  delayMicroseconds(10);
  digitalWrite(18, LOW);
  float distance = pulseIn(19, HIGH) / 58.00;
  delay(10);
  return distance;
}


void setup() {
  ledcSetup(3, 50, 10);
  ledcAttachPin(4, 3);

  pinMode(18, OUTPUT);
  pinMode(19, INPUT);

  pinMode(33, OUTPUT);
  ledcSetup(1, 1200, 8);
  ledcAttachPin(25, 1);

  pinMode(27, OUTPUT);
  ledcSetup(2, 1200, 8);
   ledcAttachPin(14, 2);

  pinMode(32, OUTPUT);
  pinMode(26, OUTPUT);
  digitalWrite(32, HIGH);
  digitalWrite(26, HIGH);
  ledcWrite(3, set_angle(90));
    delay(500);
}

void loop() {
  distance=checkdistance();
  if (!(distance < 0) && distance < 20) {
    digitalWrite(33,LOW);
    ledcWrite(1, 0);
    digitalWrite(27,LOW);
    ledcWrite(2, 0);
    delay(0.1 * 1000);
    ledcWrite(3, set_angle(180));
      delay(500);
    a1=checkdistance();
    delay(0.1 * 1000);
    ledcWrite(3, set_angle(0));
      delay(500);
    a2=checkdistance();
    delay(0.1 * 1000);
    if (a1 > a2) {
      digitalWrite(33,HIGH);
      ledcWrite(1, 180);
      digitalWrite(27,LOW);
      ledcWrite(2, 180);
      delay(0.5 * 1000);
      ledcWrite(3, set_angle(90));
        delay(400);
      delay(0.05 * 1000);
    }
    else{
      digitalWrite(33,LOW);
      ledcWrite(1, 180);
      digitalWrite(27,HIGH);
      ledcWrite(2, 180);
      delay(0.5 * 1000);
      ledcWrite(3, set_angle(90));
        delay(500);
      delay(0.05 * 1000);
    }
  }
  else{
    digitalWrite(33,LOW);
    ledcWrite(1, 180);
    digitalWrite(27,LOW);
    ledcWrite(2, 180);
  }
}
