// generated by KidsBlock
#include <Arduino.h>

void setup() {
  pinMode(4, OUTPUT);
  pinMode(5, INPUT);
}

void loop() {
  if (digitalRead(5) == 1) {
    digitalWrite(4, LOW);
  }
  else{
    digitalWrite(4, HIGH);
  }
  delay(0.05 * 1000);
}
