// generated by KidsBlock
#include <Arduino.h>

float checkdistance() {
  digitalWrite(18, LOW);
  delayMicroseconds(2);
  digitalWrite(18, HIGH);
  delayMicroseconds(10);
  digitalWrite(18, LOW);
  float distance = pulseIn(19, HIGH) / 58.00;
  delay(10);
  return distance;
}


void setup() {
  pinMode(18, OUTPUT);
  pinMode(19, INPUT);

  Serial.begin(115200);
  pinMode(18, OUTPUT);
  pinMode(19, INPUT);
}

void loop() {
  Serial.print("distance:");
  Serial.println(checkdistance());
  delay(0.3 * 1000);
}
