// generated by KidsBlock
#include <Arduino.h>

long distance = 0;

long a1 = 0;

float checkdistance() {
  digitalWrite(18, LOW);
  delayMicroseconds(2);
  digitalWrite(18, HIGH);
  delayMicroseconds(10);
  digitalWrite(18, LOW);
  float distance = pulseIn(19, HIGH) / 58.00;
  delay(10);
  return distance;
}


void setup() {
  pinMode(18, OUTPUT);
  pinMode(19, INPUT);

  pinMode(33, OUTPUT);
  ledcSetup(1, 1200, 8);
  ledcAttachPin(25, 1);

  pinMode(27, OUTPUT);
  ledcSetup(2, 1200, 8);
   ledcAttachPin(14, 2);

  pinMode(32, OUTPUT);
  pinMode(26, OUTPUT);
  digitalWrite(32, HIGH);
  digitalWrite(26, HIGH);
}

void loop() {
  distance=checkdistance();
  if (!(distance < 0) && distance < 20) {
    digitalWrite(33,LOW);
    ledcWrite(1, 0);
    digitalWrite(27,LOW);
    ledcWrite(2, 0);
    delay(0.1 * 1000);
    a1=checkdistance();
    delay(0.1 * 1000);
    if (a1 < 25) {
      digitalWrite(33,LOW);
      ledcWrite(1, 180);
      digitalWrite(27,HIGH);
      ledcWrite(2, 50);
      delay(0.2 * 1000);
    }
  }
  else{
    digitalWrite(33,LOW);
    ledcWrite(1, 180);
    digitalWrite(27,LOW);
    ledcWrite(2, 180);
  }
}
