// generated by KidsBlock
// MOTOR1 33, 25, 32
// MOTOR2 27, 14, 26
#include <Arduino.h>

void setup() {
  pinMode(33, OUTPUT);
  ledcSetup(1, 1200, 8);
  ledcAttachPin(25, 1);

  pinMode(27, OUTPUT);
  ledcSetup(2, 1200, 8);
   ledcAttachPin(14, 2);

  pinMode(32, OUTPUT); //ENABLE
  pinMode(26, OUTPUT);
  digitalWrite(32, HIGH);
  digitalWrite(26, HIGH);
}

void loop() {
  digitalWrite(33,LOW);
  ledcWrite(1, 200);
  digitalWrite(27,LOW);
  ledcWrite(2, 200);
  delay(2 * 1000);
  digitalWrite(33,HIGH);
  ledcWrite(1, 50);
  digitalWrite(27,HIGH);
  ledcWrite(2, 50);
  delay(2 * 1000);
  digitalWrite(33,HIGH);
  ledcWrite(1, 200);
  digitalWrite(27,LOW);
  ledcWrite(2, 200);
  delay(2 * 1000);
  digitalWrite(33,LOW);
  ledcWrite(1, 200);
  digitalWrite(27,HIGH);
  ledcWrite(2, 200);
  delay(2 * 1000);
  digitalWrite(33,LOW);
  ledcWrite(1, 0);
  digitalWrite(27,LOW);
  ledcWrite(2, 0);
  delay(2 * 1000);
}
